cnmb/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^start/$', views.start_admin, name='start'),
	url(r'^administrations/$', views.administrations, name='admins'),
	url(r'^administration-(?P<admin_id>[0-9]+)/$', views.admin, name='admin'),
	url(r'^administration-(?P<admin_id>[0-9]+)/section-(?P<section_num>[0-9]+)/$',
		views.section, name='section'),
	url(r'^administration-(?P<admin_id>[0-9]+)/item-(?P<item_id>[0-9]+)-upload/$', views.upload, name='upload'),
	url(r'^trainers/$', views.trainers, name='trainers'),
	url(r'^trainers/(?P<username>[0-9a-zA-Z@.+_-]+)/$', views.trainer, name='trainer'),
	url(r'^client-(?P<client_id>[0-9]+)/$', views.client, name='client'),
	url(r'^client-(?P<client_id>[0-9]+)-chart/$', views.client_chart, name='client_chart'),
	url(r'^client-(?P<client_id>[0-9]+)-media/$', views.client_media, name='client_media'),
	url(r'^clients/$', views.clients, name='clients'),
	url(r'^questions/$', views.client_questions, name='questions'),
	# Catch-all -- should be last in the list of patterns:
	url(r'^(?P<slug>[a-z0-9_-]+)/$', views.custom_page, name='custom_page'),
]

neurofit/urls.py
from django.conf.urls import include, url
from django.contrib.admin import site as admin_site
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
#from django.contrib.sites.models import Site


admin_site.site_header = 'Neuro-fit Admin'
admin_site.site_title = 'Neuro-fit Admin'
admin_site.site_url = 'https://neurofitcnmb.com/'#' + Site.objects.get_current().domain
admin_site.index_title = ''

def auth_url(name, extra_path=''):
	path = r'^%s%s/$' % (name, extra_path)
	view = getattr(auth_views, name)
	context = {'template_name': 'auth/%s.html' % name}
	if name == 'password_reset':
		context['email_template_name'] = 'auth/password_reset_email.txt'
		context['subject_template_name'] = 'auth/password_reset_subject.txt'
	return url(path, view, context, name=name)

auth_patterns = [
	auth_url('login'),
	auth_url('logout'),
	auth_url('password_reset'),
	auth_url('password_reset_done'),
	auth_url('password_reset_confirm',
			r'/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})'),
	auth_url('password_reset_complete'),
	auth_url('password_change'),
	auth_url('password_change_done'),
]

urlpatterns = [
	url(r'^$', 'cnmb.views.redirect_home'),

	url(r'^admin/', include(admin_site.urls)),

	url(r'^cnmb/', include('cnmb.urls', namespace='cnmb')),
	
	url(r'^auth/', include(auth_patterns)),

	url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cnmb/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from people.models import Client
from .models import CustomPage, Definition


class StartForm(forms.Form):
	defs = Definition.objects.filter(is_active=True).order_by('-date_created')
	clients = Client.objects.all()
	    
	definition = forms.ModelChoiceField(queryset=defs, empty_label=None) 
	client = forms.ModelChoiceField(queryset=clients)
	comments = forms.CharField(widget=forms.Textarea, required=False)


class EditAdministrationForm(forms.Form):
	comments = forms.CharField(widget=forms.Textarea, required=False)


class AdministrationMediaForm(forms.Form):
	media_file = forms.FileField()


class QuestionsForm(forms.Form):
	email = forms.EmailField(label='Your Email')
	message = forms.CharField(widget=forms.Textarea)


class CustomPageAdminForm(forms.ModelForm):
	content = forms.CharField(widget=CKEditorWidget(), required=False)

	class Meta:
		model = CustomPage
		exclude = ('slug',)

cnmb/views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.db.transaction import atomic
from django.http import HttpResponseForbidden
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from people.models import Client
from people.forms import ClientForm
from .forms import StartForm, EditAdministrationForm, AdministrationMediaForm, QuestionsForm
from .models import Administration, AdministrationMedia, CustomPage, Section, Item
from .helpers import TRAINERS_GROUP, loc_name, loc_groups

import logging
logger = logging.getLogger('cnmb')


def is_valid_user(user):
	return user.is_active and user.is_authenticated()

def is_trainer(user):
	return user.groups.filter(name=TRAINERS_GROUP).exists()

def is_valid_trainer(user):
	return is_valid_user(user) and is_trainer(user)

def is_client(user):
	return Client.objects.filter(user=user).exists()

def user_client(user):
	try:
		return Client.objects.filter(user=user).get()
	except Client.DoesNotExist:
		return None


def redirect_home(request):
	return HttpResponseRedirect(reverse('cnmb:home'))

@user_passes_test(is_valid_user)
def home(request):
	if not is_trainer(request.user):
		return HttpResponseRedirect(reverse('cnmb:client', args=[0]))
	
	recents_list = Administration.objects.filter(trainer=request.user).order_by('-date_given')[:10]
	context = {'recents_list': recents_list}
	return render(request, 'cnmb/home.html', context)

@user_passes_test(is_valid_user)
def client(request, client_id):
	if is_trainer(request.user):
		client = get_object_or_404(Client, pk=client_id)
	else:
		return client_self(request)
	
	a_list = Administration.objects.filter(client=client_id).order_by('date_given')
	
	if request.method == 'POST':
		form = ClientForm(request.POST, instance=client)
		form.save()
	else:
		form = ClientForm(instance=client)

	#if client.user:
	#	loc_list = [ loc_name(g.name) for g in loc_groups(client.user) ]
	#	client.locations = ', '.join(loc_list)
	
	context = {'client': client, 'administrations': a_list, 'form': form}
	return render(request, 'cnmb/client.html', context)

@user_passes_test(is_valid_user)
def client_self(request):
	client = user_client(request.user)
	if not client: return HttpResponseForbidden()
	
	a_list = Administration.objects.filter(client=client).order_by('date_given')

	contentA = CustomPage.objects.get(pk=1).content #hardcoded
	contentB = CustomPage.objects.get(pk=2).content #hardcoded

	context = {'client': client, 'administrations': a_list, 'contentA': contentA, 'contentB': contentB}
	return render(request, 'cnmb/client.html', context)

@user_passes_test(is_valid_user)
def client_questions(request):
	client = user_client(request.user)
	if not client: return HttpResponseForbidden()
	success = False

	if request.method == 'POST':
		form = QuestionsForm(request.POST)
		if form.is_valid():
			subj = 'Questions RE: ' + str(client)
			msg = form.cleaned_data['message']
			try:
				r = send_mail(subj, msg, form.cleaned_data['email'], ['admin@neuro-fit.com'])
			except Exception as e:
				logger.warning(u'send_mail exception: %s', e)

			if r < 1:
				logger.warning(u'send_mail returned %d sending to "%s"', r, form.email)
			else:
				success = True
	else:
		form = QuestionsForm()

	context = {'form': form, 'client': client, 'success': success}
	return render(request, 'cnmb/questions.html', context)

@user_passes_test(is_valid_user)
def client_chart(request, client_id):
	contentA = ''
	if is_trainer(request.user):
		client = get_object_or_404(Client, pk=client_id)
	else:
		client = user_client(request.user)
		if not client: return HttpResponseForbidden()
		contentA = CustomPage.objects.get(pk=5).content #hardcoded

	a_list = Administration.objects.filter(client=client).order_by('date_given')
	sections = Section.objects.filter(definition=a_list[0].definition) if len(a_list) else []

	context = {'client': client, 'administrations': a_list, 'sections': sections, 'contentA': contentA}
	return render(request, 'cnmb/client_chart.html', context)

@user_passes_test(is_valid_user)
def client_media(request, client_id):
	contentA = ''
	contentB = ''
	if is_trainer(request.user):
		client = get_object_or_404(Client, pk=client_id)
	else:
		client = user_client(request.user)
		if not client: return HttpResponseForbidden()
		contentA = CustomPage.objects.get(pk=6).content #hardcoded
		contentB = CustomPage.objects.get(pk=7).content #hardcoded

	# Go through every Administration the Client has
	final_admins = []
	a_list = Administration.objects.filter(client=client)
	for a in a_list:
		sections = {}
		m_list = AdministrationMedia.objects.filter(administration=a)
		# Go through all the media for this Administration
		for m in m_list:
			item = m.item
			s = item.section
			if s in sections:
				s_items = sections[s]
				if item in s_items:
					s_items[item].append(m)
				else:
					s_items[item] = [m]
			else:
				sections[s] = {item: [m]}
		# If any media was added for this Administration
		if len(sections) > 0:
			# Save it for the final output
			final_admins.append({'administration': a, 'sections': sections})

	context = {'client': client, 'administrations': final_admins, 'contentA': contentA, 'contentB': contentB}
	return render(request, 'cnmb/client_media.html', context)

@user_passes_test(is_valid_trainer)
def clients(request):
	locations = []
	# For each location that current trainer has
	for g in loc_groups(request.user):
		# Get clients at that location
		c_list = Client.objects.filter(location_group=g)
		locations.append({'name': loc_name(g.name), 'clients': c_list})

	#OLD: Get all clients
	#c_list = Client.objects.order_by('location_group', 'last_name', 'first_name')
	#context = {'clients': c_list}

	context = {'locations': locations}
	return render(request, 'cnmb/clients.html', context)

@user_passes_test(is_valid_trainer)
def start_admin(request):
	if request.method == 'POST':
		form = StartForm(request.POST)
		if form.is_valid():
			definition = form.cleaned_data['definition']
			client = form.cleaned_data['client']
			comments = form.cleaned_data['comments']
			a = Administration(definition=definition, client=client, 
							trainer=request.user, comments=comments)
			a.save()
			return HttpResponseRedirect(reverse('cnmb:section', args=(a.pk, 1)))
	else:
		form = StartForm()
	
	return render(request, 'cnmb/start.html', {'form': form})

@user_passes_test(is_valid_trainer)
def administrations(request):
	a_list = Administration.objects.order_by('-date_given')
	context = {'administrations': a_list}
	return render(request, 'cnmb/administrations.html', context)

@user_passes_test(is_valid_user)
def admin(request, admin_id):
	a = get_object_or_404(Administration, pk=admin_id)

	contentA = ''
	contentB = ''
	trainer = is_trainer(request.user)
	if not trainer:
		client = user_client(request.user)
		if (not client) or (client.id != a.client.id):
			return HttpResponseForbidden()
		contentA = CustomPage.objects.get(pk=3).content #hardcoded
		contentB = CustomPage.objects.get(pk=4).content #hardcoded

	saved = False
	if trainer:
		if request.method == 'POST':
			form = EditAdministrationForm(request.POST)
			if form.is_valid():
				comments = form.cleaned_data['comments']
				a.comments = comments
				a.save()
				saved = True
		else:
			form = EditAdministrationForm(initial={'comments': a.comments})
	else:
		form = None
	
	sections = Section.objects.filter(definition=a.definition)
	total_score = 0
	max_score = 0
	for section in sections:
		max_score += section.max_score()
		t = a.section_score(section)
		total_score += t
		section.total_score = t  # Save for template
	
	context = {'admin': a, 'sections': sections,
			'total_score': total_score, 'max_score': max_score, 
			'form': form, 'saved': saved,
			'contentA': contentA, 'contentB': contentB}
	return render(request, 'cnmb/admin.html', context)

@user_passes_test(is_valid_trainer)
def trainers(request):
	u_list = User.objects.filter(groups__name=TRAINERS_GROUP).order_by('last_name')
	locations = {}
	unknowns = []
	for u in u_list:
		any_location = False
		for g in loc_groups(u):
			if g.name in locations:
				locations[g.name].append(u)
			else:
				locations[g.name] = [u]
			any_location = True
		if not any_location:
			unknowns.append(u)
	
	loc_list = []
	for gname in sorted(locations):
		loc_list.append({'name': loc_name(gname), 'users': locations[gname]})
	if unknowns:
		loc_list.append({'name': 'Unknown Location', 'users': unknowns})

	#context = {'users': u_list}
	context = {'locations': loc_list}
	return render(request, 'cnmb/trainers.html', context)

@user_passes_test(is_valid_trainer)
def trainer(request, username):
	u = get_object_or_404(User, username=username)
	a_list = Administration.objects.filter(trainer=u).order_by('-date_given')
	context = {'page_user': u, 'administrations': a_list}
	return render(request, 'cnmb/trainer.html', context)

def save_POST_score(a, item, score_val):
	if score_val is None: # Ignore this Item
		logger.info(u'Missing expected POST field item-%d', item.pk)
	elif not score_val: # Remove any current Score
		for s in item.sel_scores:
			logger.debug(u'Removing score-num %d for item %d', s.score, item.pk)
			a.scores.remove(s)
	else: # Remove any current Score and add new one
		try:
			score_num = int(score_val)
		except ValueError:
			logger.warning(u'Could not convert POST[item-%d]="%s" to int', item.pk, score_val)
			return
		logger.debug(u'Got score-num %d for item %d', score_num, item.pk)
		new_score = None
		for s in item.score_set.all():
			if s.score == score_num:
				new_score = s
				break
		if new_score is None:
			logger.warning(u'...score-num %d does not exist for item %d', score_num, item.pk)
			return
		for s in item.sel_scores:
			if s.score == score_num:

cnmb/templates/cnmb/admin.html
{% extends "cnmb/base.html" %}
{% load cnmb_extras %}

{% block title %}Administration - {% endblock %}

{% block body %}

{% if not user|is_trainer %}
<div style="float:right;width:500px;">{{ contentA|safe }}</div>
{% endif %}

<h1>CNMB Administration</h1>

{% if user|is_trainer %}
  {% if saved %} {# <p class="msg">The data has been saved.</p> #} {% endif %}
  <form method="post" action="">
  {% csrf_token %}
  <table class="form">
  <tr><th>CNMB Definition:</th><td>{{ admin.definition }}</td></tr>
  <tr><th>Client:</th><td><a href="{% url 'cnmb:client' admin.client.id %}">{{ admin.client }}</a></td></tr>
  <tr><th>Trainer:</th><td><a href="{% url 'cnmb:trainer' admin.trainer.username %}">{{ admin.trainer|user_nice }}</a></td></tr>
  <tr><th>Date Started:</th><td>{{ admin.date_given }}</td></tr>
  {{ form }}
  <tr class="form_footer"><td colspan="2"><input type="submit" value="Save"></td></tr>
  </table>
  </form>
{% else %}
  <table class="form">
  <tr><th>Client:</th><td>{{ admin.client }}</td></tr>
  <tr><th>Trainer:</th><td>{{ admin.trainer|user_nice }}</td></tr>
  <tr><th>Date Started:</th><td>{{ admin.date_given }}</td></tr>
  </table>
  &nbsp;
{% endif %}


<h2>Sections</h2>
<table class="grid r">
<tr class="headfoot"><th>#</th><th class="l">Name</th><th>Score</th><th>Max</th></tr>
{% for section in sections %}
<tr>
    <td>{{ section.number }}</td>
    <td class="l">
      {% if user|is_trainer %}
        <a href="{% url 'cnmb:section' admin.id section.number %}">{{ section.title }}</a>
      {% else %}
        {{ section.title }}
      {% endif %}
    </td>
    <td>{{ section.total_score }}</td>
    <td>{{ section.max_score }}</td>
</tr>
{% endfor %}
<tr class="headfoot">
    <td></td>
    <th>TOTAL</th>
    <th>{{ total_score }}</th>
    <th>{{ max_score }}</th>
</tr>
</table>
<div id="chart1"></div>

{% if not user|is_trainer %}
<div>{{ contentB|safe }}</div>
{% endif %}

{% endblock %}

{% block head %}
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
google.load('visualization', '1', {packages:['corechart']});
google.setOnLoadCallback(drawCharts);
function drawCharts() {
var data = google.visualization.arrayToDataTable([
	['Section', 'Score', {role:'tooltip'}, {role:'annotation'}],
{% for section in sections %}
	['{{ section.number }}', {{ section.total_score }} / {{ section.max_score }}, Math.round(100*{{ section.total_score }}/{{ section.max_score }})+'%', {{section.total_score}} ],
{% endfor %}
	['TOTAL', {{ total_score }} / {{ max_score }}, Math.round(100*{{ total_score }}/{{ max_score }})+'%', {{total_score}} ],
]);
var options = {
	width: 600,
	height: 350,
	chartArea: {left:50, width:'100%'},
	legend: {position:'none'},
	colors: ['#1e3e88'],
	vAxis: {minValue:0, maxValue:1, format:'percent'},
	//tooltip: {trigger:'none'},
};
var chart = new google.visualization.ColumnChart(document.getElementById('chart1'));
chart.draw(data, options);
}
</script>
{% endblock %}

cnmb/templates/cnmb/administrations.html
{% extends "cnmb/base.html" %}

{% block title %}Administrations - {% endblock %}

{% block body %}

<h1>CNMB Administrations</h1>

{% if administrations %}
<ul>
{% for admin in administrations %}
    <li><a href="{% url 'cnmb:admin' admin.id %}">{{ admin.client }} on {{ admin.date_given }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>There are no CNMB administrations yet.</p>
{% endif %}

{% endblock %}

cnmb/templates/cnmb/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load cnmb_extras %}
<head>
<meta charset="utf-8">
<title>{% block title %}{% endblock %}CNMB</title>
<link rel="stylesheet" href="{% static 'cnmb/css/base.css' %}">
{% block head %}{% endblock %}
</head>
<body>
<div id="header">
{% block header %}
<div id="header_user">
{% if user.is_authenticated %}
Logged in as <em>{{ user }}</em> (<a href="{% url 'logout' %}">logout</a>)
<br>(<a href="{% url 'password_change' %}">change password</a>)
{% else %}
<a href="{% url 'cnmb:home' %}">Login</a>
{% endif %}
</div>
<table><tr>
<td><a href="http://www.neuro-fit.com/" target="_blank"><img src="{% static "images/neurofit_sm.png" %}" alt="Neuro-fit" width="220" height="50"></a></td>
{% if user.is_authenticated %}
    <td><a href="{% url 'cnmb:home' %}">Home</a></td>
  {% if user|is_trainer %}
    <td><a href="{% url 'cnmb:clients' %}">Clients</a></td>
    {# <td><a href="{% url 'cnmb:admins' %}">CNMBs</a></td> #}
    <td><a href="{% url 'cnmb:trainers' %}">Trainers</a></td>
    <td><a href="{% url 'cnmb:start' %}">Start New CNMB</a></td>
    {% if user.is_staff %}
    <td><a href="{% url 'admin:index' %}">Site Admin</a></td>
    {% endif %}
  {% elif user|is_client %}
    <td><a href="{% url 'cnmb:questions' %}">Questions?</a></td>
  {% endif %}

  {# Custom pages #}
  {% get_nav_custom_pages user as nav_pages %}
  {% for page in nav_pages %}
    <td><a href="{% url 'cnmb:custom_page' page.slug %}">{{ page.title }}</a></td>
  {% endfor %}

{% else %}
    <td><a href="{% url 'cnmb:home' %}">Login</a></td>
{% endif %}
</tr></table>
{% endblock %}
</div>
{% block subheader %}{% endblock %}
<div id="content">
{% block body %}{% endblock %}
</div>
</body>
</html>

cnmb/templates/cnmb/client.html
{% extends "cnmb/base.html" %}
{% load cnmb_extras %}

{% block title %}Client: {{ client.first_name }} {{ client.last_name }} - {% endblock %}

{% block body %}

{% if user|is_trainer %}
<h1>Client</h1>
<form method="post" action="">
{% csrf_token %}
<table class="form">
<tr><th>First Name:</th><td>{{ client.first_name }}</td></tr>
<tr><th>Last Name:</th><td>{{ client.last_name }}</td></tr>
<tr><th>Gender:</th><td>{{ client.gender }}</td></tr>
<tr><th>Birthday:</th><td>{{ client.birthday|default:"" }}</td></tr>
<tr><th>Parent:</th><td>{{ client.parent }}</td></tr>
<tr><th>Email:</th><td>{{ client.email }}</td></tr>
<tr><th>Phone:</th><td>{{ client.phone }}</td></tr>
<tr><th>User Account:</th><td>{{ client.user|user_nice }}</td></tr>
<tr><th>Location:</th><td>{{ client.location }}</td></tr>
{{ form }}
<tr class="form_footer"><td colspan="2"><input type="submit" value="Save"></td></tr>
</table>
</form>
{% else %}
<div style="float:right;width:500px;">{{ contentA|safe }}</div>
<h1>Client: {{ client }}</h1>
{% endif %}

{% if administrations %}
<h2>{{ administrations|length }} Administration{{ administrations|length|pluralize }}:</h2>
<table class="grid">
<tr class="headfoot">{#<th></th>#}<th>Date</th><th>CNMB Definition</th><th>Score</th></tr>
{% for a in administrations %}
<tr>
	{#<td><a href="{% url 'cnmb:admin' a.id %}">View</a></td>#}
	<td><a href="{% url 'cnmb:admin' a.id %}">{{ a.date_given }}</a></td>
	<td>{{ a.definition }}</td>
	<td class="r">{{ a.total_score }}</td>
</tr>
{% endfor %}
</table>
<p><a href="{% url 'cnmb:client_chart' client.id %}">View Complete Chart</a></p>
<p><a href="{% url 'cnmb:client_media' client.id %}">View All Media</a></p>
{% endif %}

{% if user|is_client %}
<div>{{ contentB|safe }}</div>
{% endif %}

{% endblock %}

cnmb/templates/cnmb/home.html
{% extends "cnmb/base.html" %}

{% block title %}Home - {% endblock %}

{% block body %}

{% comment %}
<h1>CNMB Home</h1>
<p><a href="{% url 'cnmb:start' %}">Start a new CNMB administration</a></p>
<p><a href="{% url 'cnmb:admins' %}">View all CNMB administrations</a></p>
<p><a href="{% url 'cnmb:clients' %}">View all clients</a></p>
{% endcomment %}

<h2>Your recent CNMB administrations</h2>
{% if recents_list %}
<ul>
{% for admin in recents_list %}
    <li><a href="{% url 'cnmb:admin' admin.id %}">{{ admin.client }} on {{ admin.date_given }}</a>
    {# (<a href="{% url 'cnmb:client' admin.client.id %}">client</a>) #}</li>
{% endfor %}
</ul>
{% else %}
<p>You haven't administered any CNMBs.</p>
{% endif %}

{% endblock %}

cnmb/templates/cnmb/section.html
{% extends "cnmb/base.html" %}
{% load staticfiles %}

{% block title %}[{{ section.number }}] {{ section.title }} - {% endblock %}

{% block subheader %}

<table id="section_links"><tr class="links">
{% for s in sections %}
<td>
{% if s.number == section.number %}
    <a href="" class="sel">{{ s.title }}</a>
{% else %}
    <a href="{% url 'cnmb:section' admin.id s.number %}">{{ s.title }}</a>
{% endif %}
</td>
{% endfor %}
</tr></table>

{% endblock %}

{% block body %}

<table class="form rfloat">
<tr><th>Client:</th><td><a href="{% url 'cnmb:client' admin.client.id %}">{{ admin.client }}</a></td></tr>
<tr><th>Started:</th><td>{{ admin.date_given }}</td></tr>
<tr><td colspan="2"><a href="{% url 'cnmb:admin' admin.id %}">View Summary</a></td></tr>
</table>

<h1>CNMB Administration</h1>
<h2>Section {{ section.number }}: {{ section.title }}</h2>

<form method="post" action="" class="clear">
{% csrf_token %}

<table class="items">
{% for item in items %}

<tr><th colspan="2"><em>{{ item.number }}: {{ item.name }}</em></th></tr>
<tr>
<td class="desc">
  {{ item.description }}

  <div style="border-top:1px solid #ccc; margin-top:1em;">
    <div style="float:right;"><a href="{% url 'cnmb:upload' admin.id item.id %}" target="_blank"><img src="{% static 'admin/img/icon_addlink.gif' %}" alt="+"> Upload media</a></div>
  {% for m in item.admin_media %}
  <a href="{{ m.media_file.url }}" target="_blank">{{ m.filename }}</a><br>
  {% endfor %}
  {# <input type="file" name="item-{{ item.id }}-media"> #}
  </div>
</td>
<td>
<ol class="scores">
{% for score in item.score_set.all %}
    <li>
    <input type="radio" name="item-{{ item.id }}" id="item-{{ item.id }}-score-{{ score.score }}" value="{{ score.score }}" {% if score in item.sel_scores %}checked{% endif %}>
    <label for="item-{{ item.id }}-score-{{ score.score }}">
    <table><tr><th>{{ score.score }}</th><td>{{ score.description }}</td></tr></table>
    </label>
    </li>
{% endfor %}
    <li>
    <input type="radio" name="item-{{ item.id }}" id="item-{{ item.id }}-noscore" value="" {% if not item.sel_scores %}checked{% endif %}>
    <label for="item-{{ item.id }}-noscore">No score</label>
    </li>
</ol>
</td>
</tr>

{% endfor %}
</table>

<hr>
<input type="submit" value="Save and Continue">
</form>

{% endblock %}

cnmb/templates/cnmb/start.html
{% extends "cnmb/base.html" %}

{% block title %}Start New - {% endblock %}

{% block body %}

<h1>Start CNMB Administration</h1>

<form method="post" action="">
{% csrf_token %}
<table class="form">
{{ form }}
<tr class="form_footer"><td colspan="2"><input type="submit" value="Start CNMB"></td></tr>
</table>
</form>

{% endblock %}

cnmb/templates/cnmb/trainer.html
{% extends "cnmb/base.html" %}
{% load cnmb_extras %}
{% block title %}{{ page_user|user_nice }} - {% endblock %}

{% block body %}

<h1>Trainer</h1>

<table class="form">
<tr><th>Name</th><td>{{ page_user|user_nice }}</td></tr>
<tr><th>Email</th><td>{{ page_user.email }}</td></tr>
</table>

<br>

<h2>All Administrations:</h2>
{% if administrations %}
<table class="grid">
<tr class="headfoot">{#<th></th>#}<th>Date</th><th>Client</th></tr>
{% for a in administrations %}
    {#<tr><td><a href="{% url 'cnmb:admin' a.id %}">View</a></td>#}
    <td><a href="{% url 'cnmb:admin' a.id %}">{{ a.date_given }}</a></td>
    <td><a href="{% url 'cnmb:client' a.client.id %}">{{ a.client }}</a></td></tr>
{% endfor %}
</table>
{% else %}
<p>This trainer has not administered any CNMBs yet.</p>
{% endif %}

{% endblock %}